//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace end_user_gui.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("end_user_gui.App_GlobalResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string cart_add {
            get {
                return ResourceManager.GetString("cart_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add archive.
        /// </summary>
        public static string cart_addtitle {
            get {
                return ResourceManager.GetString("cart_addtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available DIPs.
        /// </summary>
        public static string cart_availabledisseminations {
            get {
                return ResourceManager.GetString("cart_availabledisseminations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cart_cancel {
            get {
                return ResourceManager.GetString("cart_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset cart.
        /// </summary>
        public static string cart_clear {
            get {
                return ResourceManager.GetString("cart_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string cart_close {
            get {
                return ResourceManager.GetString("cart_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string cart_items {
            get {
                return ResourceManager.GetString("cart_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a new DIP.
        /// </summary>
        public static string cart_newdip {
            get {
                return ResourceManager.GetString("cart_newdip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string cart_remove {
            get {
                return ResourceManager.GetString("cart_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit order.
        /// </summary>
        public static string cart_submit {
            get {
                return ResourceManager.GetString("cart_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks, I need a new DIP.
        /// </summary>
        public static string cart_thanksnewdip {
            get {
                return ResourceManager.GetString("cart_thanksnewdip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string cart_view {
            get {
                return ResourceManager.GetString("cart_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search query.
        /// </summary>
        public static string main_entersearchterrm {
            get {
                return ResourceManager.GetString("main_entersearchterrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Ark Web.
        /// </summary>
        public static string navbar_brand {
            get {
                return ResourceManager.GetString("navbar_brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string navbar_home {
            get {
                return ResourceManager.GetString("navbar_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string navbar_profile {
            get {
                return ResourceManager.GetString("navbar_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (None).
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found matches.
        /// </summary>
        public static string search_foundtitle {
            get {
                return ResourceManager.GetString("search_foundtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name :.
        /// </summary>
        public static string search_nametitle {
            get {
                return ResourceManager.GetString("search_nametitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search_search {
            get {
                return ResourceManager.GetString("search_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My orders.
        /// </summary>
        public static string userorders_myorders {
            get {
                return ResourceManager.GetString("userorders_myorders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string userorders_username {
            get {
                return ResourceManager.GetString("userorders_username", resourceCulture);
            }
        }
    }
}
